id: 25b9c01c-350d-4b95-bed1-836d04a4f324
logsource:
  product: linux
title: Chkconfig Service Add
description: >-
  Detects the use of the chkconfig binary to manually add a service for
  management by chkconfig. Threat actors may utilize this technique to maintain
  persistence on a system. When a new service is added, chkconfig ensures that
  the service has either a start or a kill entry in every runlevel and when the
  system is rebooted the service file added will run providing long-term
  persistence.
tags:
  - attack.persistence
  - attack.TA0003
  - attack.t1037
  - attack.t1037.004
falsepositives:
  - >-
    Legitimate use of chkconfig to add services by system administrators or
    automated tools
level: medium
status: experimental
references: []
author: contains
detection:
  condition: selection and (filter1 or filter2) and not (filter3 and filter4)
  selection:
    host.os.type|all:
      - linux
    event.action|contains:
      - exec
      - exec_event
      - executed
  filter3:
    process.name|contains:
      - rpm
      - qualys-scan-util
      - qualys-cloud-agent
      - update-alternatives
  filter4:
    process.args|contains:
      - /var/tmp/rpm*
      - /var/lib/waagent/*
  filter1:
    process.executable|all:
      - usr/sbin/chkconfig
    process.args|contains:
      - '--add'
  filter2:
    process.args|contains:
      - '--add'
