id: 25b9c01c-350d-4b95-bed1-836d04a4f324
logsource:
  product: linux
title: Shell Configuration Creation or Modification
description: >-
  This rule monitors the creation/alteration of a shell configuration file. Unix
  systems use shell configuration files to set environment variables, create
  aliases, and customize the users environment. Adversaries may modify or add a
  shell configuration file to execute malicious code and gain persistence in the
  system. This behavior is consistent with the Kaiji malware family.
tags:
  - attack.persistence
  - attack.TA0003
  - attack.t1546
  - attack.t1546.004
falsepositives:
  - Legitimate user shell modification activity
level: medium
status: experimental
references: []
author: hoang.nguyen
detection:
  condition: >-
    selection and not (filter1 or filter2 or filter3 or filter4 or filter5 or
    filter6 or filter7)
  selection:
    host.os.type|all:
      - linux
    event.action|contains:
      - rename
      - creation
      - create
    file.path|contains:
      - /etc/profile
      - /etc/profile.d/*
      - /etc/bash.bashrc
      - /etc/zsh/*
      - /etc/csh.cshrc
      - /etc/csh.login
      - /etc/fish/config.fish
      - /etc/ksh.kshrc
      - /home/*/.profile
      - /home/*/.bashrc
      - /home/*/.bash_login
      - /home/*/.bash_logout
      - /root/.profile
      - /root/.bashrc
      - /root/.bash_login
      - /root/.bash_logout
      - /home/*/.zprofile
      - /home/*/.zshrc
      - /root/.zprofile
      - /root/.zshrc
      - /home/*/.cshrc
      - /home/*/.login
      - /home/*/.logout
      - /root/.cshrc
      - /root/.login
      - /root/.logout
      - /home/*/.config/fish/config.fish
      - /root/.config/fish/config.fish
      - /home/*/.kshrc
      - /root/.kshrc
  filter1:
    process.executable|contains:
      - /bin/dpkg
      - /usr/bin/dpkg
      - /bin/dockerd
      - /usr/bin/dockerd
      - /usr/sbin/dockerd
      - /bin/microdnf
      - /usr/bin/microdnf
      - /bin/rpm
      - /usr/bin/rpm
      - /bin/snapd
      - /usr/bin/snapd
      - /bin/yum
      - /usr/bin/yum
      - /bin/dnf
      - /usr/bin/dnf
      - /bin/podman
      - /usr/bin/podman
      - /bin/dnf-automatic
      - /usr/bin/dnf-automatic
      - /bin/pacman
      - /usr/bin/pacman
      - /usr/bin/dpkg-divert
      - /bin/dpkg-divert
      - /sbin/apk
      - /usr/sbin/apk
      - /usr/local/sbin/apk
      - /usr/bin/apt
      - /usr/sbin/pacman
      - /usr/bin/puppet
      - /bin/puppet
      - /opt/puppetlabs/puppet/bin/puppet
      - /usr/bin/chef-client
      - /bin/chef-client
      - /bin/autossl_check
      - /usr/bin/autossl_check
      - /proc/self/exe
      - /dev/fd/*
      - /usr/bin/pamac-daemon
      - /bin/pamac-daemon
      - /usr/lib/snapd/snapd
      - /usr/sbin/adduser
      - /usr/sbin/useradd
      - /usr/local/bin/dockerd
  filter2:
    file.extension|contains:
      - swp
      - swpx
      - swx
      - dpkg-remove
  filter3:
    file.extension|all:
      - dpkg-new
  filter4:
    process.executable|contains:
      - /nix/store/*
      - /var/lib/dpkg/*
      - /tmp/vmis.*
      - /snap/*
      - /dev/fd/*
      - /usr/lib/virtualbox/*
  filter5:
    process.executable:
      - 'null'
  filter6:
    process.name|all:
      - sed
    file.name|all:
      - sed*
  filter7:
    process.name|all:
      - perl
    file.name|all:
      - e2scrub_all.tmp*
