id: ""
logsource:
  product: linux
title: Process Discovery via Built-In Applications
description: >-
  Identifies the use of built-in tools attackers can use to discover running
  processes on an endpoint.
tags:
  - attack.Discovery
  - attack.TA0007
  - attack.T1057
  - attack.T1518
  - attack.T1518.001
  - attack.auditbeat
falsepositives: []
level: low
status: experimental
references:
  - 'https://attack.mitre.org/tactics/TA0007/'
  - 'https://attack.mitre.org/techniques/T1057/'
  - 'https://attack.mitre.org/techniques/T1518/'
  - 'https://attack.mitre.org/techniques/T1518/001/'
author: hoang.nguyen
detection:
  condition: Selection_1 and Selection_2 and Selection_3
  Selection_1:
    event.type|contains:
      - start
  Selection_2:
    event.action|contains:
      - exec
      - exec_event
      - executed
  Selection_3:
    process.name|contains:
      - ps
      - pstree
      - htop
      - pgrep
